// examples/integ-vue/src/components/Alert.vue
<script setup lang="ts">
defineProps<{
  type?: 'info' | 'warning' | 'error' | 'success';
  title?: string;
}>();
</script>

<template>
  <div :class="['alert', `alert-${type ?? 'info'}`]">
    <strong v-if="title">{{ title }}</strong>
    <slot />
  </div>
</template>

<style scoped>
.alert {
  padding: 1rem;
  border-radius: 0.5rem;
  margin: 1rem 0;
}

.alert-info {
  background: #dbeafe;
  border-left: 4px solid #3b82f6;
}

.alert-warning {
  background: #fef3c7;
  border-left: 4px solid #f59e0b;
}

.alert-error {
  background: #fee2e2;
  border-left: 4px solid #ef4444;
}

.alert-success {
  background: #dcfce7;
  border-left: 4px solid #22c55e;
}
</style>

// examples/integ-svelte/src/components/Alert.svelte
<script>
  let { type = 'info', title = '', children } = $props();

  const colors = {
    info: { bg: '#1e3a5f', border: '#3b82f6' },
    warning: { bg: '#422006', border: '#f59e0b' },
    error: { bg: '#450a0a', border: '#ef4444' },
    success: { bg: '#052e16', border: '#22c55e' },
  };

  $: color = colors[type] || colors.info;
</script>

<div
  class="alert"
  style="background: {color.bg}; border-left: 4px solid {color.border};"
>
  {#if title}
    <strong>{title}</strong>
  {/if}
  {@render children?.()}
</div>

<style>
  .alert {
    padding: 1rem;
    border-radius: 0.5rem;
    margin: 1rem 0;
  }

  strong {
    display: block;
    margin-bottom: 0.5rem;
  }
</style>
